-- materia
ALTER TABLE materia ADD COLUMN IF NOT EXISTS descricao VARCHAR(255);
ALTER TABLE materia ADD COLUMN IF NOT EXISTS ativo BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE materia ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;

-- questao
ALTER TABLE questao ADD COLUMN IF NOT EXISTS imagem_url VARCHAR(500);
ALTER TABLE questao ADD COLUMN IF NOT EXISTS has_latex BOOLEAN DEFAULT false;
ALTER TABLE questao ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;

-- usuario
ALTER TABLE usuario ADD COLUMN IF NOT EXISTS apelido VARCHAR(30);
ALTER TABLE usuario ADD COLUMN IF NOT EXISTS foto_url VARCHAR(500);
ALTER TABLE usuario ADD COLUMN IF NOT EXISTS role VARCHAR(20) NOT NULL DEFAULT 'USER';
ALTER TABLE usuario ADD COLUMN IF NOT EXISTS password_hash VARCHAR(255);
ALTER TABLE usuario ADD COLUMN IF NOT EXISTS ultimo_acesso TIMESTAMP;

-- tentativa_simulado
ALTER TABLE tentativa_simulado ADD COLUMN IF NOT EXISTS em_branco INTEGER;
ALTER TABLE tentativa_simulado ADD COLUMN IF NOT EXISTS pontuacao INTEGER;

-- resposta_questao
ALTER TABLE resposta_questao ADD COLUMN IF NOT EXISTS tipo_resultado VARCHAR(50);
ALTER TABLE resposta_questao ADD COLUMN IF NOT EXISTS caderno VARCHAR(30);