ALTER TABLE questao ADD COLUMN IF NOT EXISTS banca_orgao VARCHAR(200);
ALTER TABLE questao ADD COLUMN IF NOT EXISTS link VARCHAR(255);
ALTER TABLE questao ADD COLUMN IF NOT EXISTS id_tec VARCHAR(20);
ALTER TABLE questao ADD COLUMN IF NOT EXISTS comando TEXT;
ALTER TABLE questao ADD COLUMN IF NOT EXISTS id_assunto BIGINT REFERENCES assunto(id);
ALTER TABLE questao ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;