ALTER TABLE assunto ADD COLUMN IF NOT EXISTS descricao VARCHAR(255);
ALTER TABLE assunto ADD COLUMN IF NOT EXISTS ativo BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE assunto ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;