spring:
  application:
    name: rinhadeconcurseiro

  # Banco de Dados
  datasource:
    url: jdbc:postgresql://localhost:5432/rinhadeconcurseiro
    username: postgres
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

  # JPA / Hibernate
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: ${JPA_FORMAT_SQL:false}

  #Flyway
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 3
    locations: classpath:db/migration
    validate-on-migrate: false

  # OAuth2 (configuraremos depois)
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid, profile, email

# Logging
logging:
  level:
    root: ${ROOT_LOG_LEVEL:INFO}
    org.springframework.security: ${SPRING_SECURITY_LOG_LEVEL:DEBUG}
    org.springframework.security.oauth2: ${SPRING_SECURITY_OAUTH2_LOG_LEVEL:DEBUG}
    org.springframework.web.client: ${SPRING_WEB_CLIENT_LOG_LEVEL:WARN}
    org.hibernate.SQL: ${HIBERNATE_SQL_LOG_LEVEL:WARN}
    org.hibernate.type.descriptor.sql: ${HIBERNATE_BINDER_LOG_LEVEL:WARN}
    br.com.rinhadeconcurseiro: ${APP_LOG_LEVEL:INFO}
    org.flywaydb: ${FLYWAY_LOG_LEVEL:INFO}
    org.springframework.boot.autoconfigure.flyway: ${FLYWAY_AUTOCONFIG_LOG_LEVEL:INFO}

# Servidor
server:
  port: 8080

# Frontend URL 
app:
  frontend:
    url: http://localhost:5173
  cors:
    allowed-origins: http://localhost:5173

debug: ${APP_DEBUG:false}
